kicksbyfujo/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):

    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

kicksbyfujo/__init__.py
from flask import Flask
from flask_assets import Environment, Bundle
from config import Config
from kicksbyfujo.main.views import home


app = Flask(__name__)
app.config.from_object(Config)
app.config['ASSETS_DEBUG'] = True

bundles = {
    'home_js': Bundle(
        'js/jquery.js',
        'js/jquery.smartmenus.min.js',
        'js/queryloader2.min.js',
        'js/jquery.carouFredSel-6.0.0-packed.js',
        'js/jquery.mousewheel.min.js',
        'js/jquery.touchSwipe.min.js',
        'js/jquery.easing.1.3.js',
        'js/jquery.nicescroll.min.js',
        'js/main.js',
        filters='jsmin',
        output='gen/home.js'
    ),
    'home_css': Bundle(
        'css/carouFredSel.css',
        'css/clear.css',
        'css/common.css',
        'css/font-awesome.min.css',
        'css/sm-clean.css',
        'style.css',
        filters='cssmin',
        output='gen/home.css'
    )

}
assets = Environment(app)

assets.register(bundles)

app.register_blueprint(home)

kicksbyfujo/main/views.py
from flask import render_template,redirect,Blueprint
from kicksbyfujo.main.forms import LoginForm
home = Blueprint('home', __name__)

@home.route('/')
@home.route('/index')
def index():
    return render_template("index.html")
@home.route('/login')
def login():
    form = LoginForm()
    return render_template('contact.html',form=form)

kicksbyfujo/templates/about2.html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>Katt - Tasty Blog Html Template</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Template by Colorlib" />
        <meta name="keywords" content="HTML, CSS, JavaScript, PHP" />
        <meta name="author" content="Colorlib" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link rel="shortcut icon" href="images/favicon.png" />
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700%7CPT+Serif:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css"  href='css/clear.css' />
        <link rel="stylesheet" type="text/css"  href='css/common.css' />
        <link rel="stylesheet" type="text/css"  href='css/font-awesome.min.css' />
        <link rel="stylesheet" type="text/css"  href='css/carouFredSel.css' />
        <link rel="stylesheet" type="text/css"  href='css/sm-clean.css' />
        <link rel="stylesheet" type="text/css"  href='style.css' />

        <!--[if lt IE 9]>
                <script src="js/html5.js"></script>
        <![endif]-->

    </head>

    <body class="about page page-template-default">
        <div class="doc-loader"></div>

        <div class="content-1170 header-holder center-relative">
            <div class="header-logo left">
                <a href="index.html">
                    <img src="images/katt_default_logo.png" alt="Katt">
                </a>
            </div>

            <div class="header-menu">
                <div class="toggle-holder relative">
                    <div id="toggle">
                        <div class="one"></div>
                        <div class="two"></div>
                        <div class="three"></div>
                    </div>
                </div>

                <nav id="header-main-menu" class="big-menu">
                    <ul class="main-menu sm sm-clean">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="about.html">About</a></li>
                        <li><a href="about2.html" class="current">About 2</a></li>
                        <li><a href="about3.html">About 3</a></li>
                        <li><a href="contact.html">Contact</a>
                            <ul class="sub-menu">
                                <li><a href="contact2.html">Contact + Map</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>


        <div id="content" class="site-content">
            <div class="header-image">
                <h1 class="entry-title">About</h1>
                <img src="demo-images/katt_about_image01.jpg" alt="">
            </div>

            <article class="content-1170 center-relative">
                <div class="content-wrapper">
                    <div class="entry-content">
                        <p>
                            <strong>State of our company</strong>
                            <br>
                            Because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone and one.
                        </p>
                        <br>
                        <br>
                        <div class="team-holder ">
                            <div class="member one_half">
                                <img src="demo-images/katt_about_image02.jpg" alt="">
                                <div class="member-info">
                                    <div class="member-name">John Doe</div>
                                    <div class="member-social-holder">
                                        <p>Quisque feugiat condimentum neque et mattis</p>
                                        <br>
                                        <div class="social"><a href="http://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></div>
                                        <div class="social"><a href="http://facebook.com" target="_blank"><i class="fa fa-facebook"></i></a></div>
                                        <div class="social"><a href="http://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="member one_half">
                                <img src="demo-images/katt_about_image03.jpg" alt="">
                                <div class="member-info">
                                    <div class="member-name">John Doe</div>
                                    <div class="member-social-holder">
                                        <p>Quisque feugiat condimentum neque et mattis</p>
                                        <br>
                                        <div class="social"><a href="http://google.com" target="_blank"><i class="fa fa-google-plus-square"></i></a></div>
                                        <div class="social"><a href="http://dribbble.com" target="_blank"><i class="fa fa-dribbble"></i></a></div>
                                        <div class="social"><a href="http://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="member one_half">
                                <img src="demo-images/katt_about_image07.jpg" alt="">
                                <div class="member-info">
                                    <div class="member-name">John Doe</div>
                                    <div class="member-social-holder">
                                        <p>Quisque feugiat condimentum neque et mattis</p>
                                        <br>
                                        <div class="social"><a href="http://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></div>
                                        <div class="social"><a href="http://facebook.com" target="_blank"><i class="fa fa-facebook"></i></a></div>
                                        <div class="social"><a href="http://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="member one_half">
                                <img src="demo-images/katt_about_image04.jpg" alt="">
                                <div class="member-info">
                                    <div class="member-name">John Doe</div>
                                    <div class="member-social-holder">
                                        <p>Quisque feugiat condimentum neque et mattis</p>
                                        <br>
                                        <div class="social"><a href="http://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></div>
                                        <div class="social"><a href="http://facebook.com" target="_blank"><i class="fa fa-facebook"></i></a></div>
                                        <div class="social"><a href="http://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="member one_half">
                                <img src="demo-images/katt_about_image05.jpg" alt="">
                                <div class="member-info">
                                    <div class="member-name">John Doe</div>
                                    <div class="member-social-holder">
                                        <p>Quisque feugiat condimentum neque et mattis</p>
                                        <br>
                                        <div class="social"><a href="http://google.com" target="_blank"><i class="fa fa-google-plus-square"></i></a></div>
                                        <div class="social"><a href="http://dribbble.com" target="_blank"><i class="fa fa-dribbble"></i></a></div>
                                        <div class="social"><a href="http://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="member one_half">
                                <img src="demo-images/katt_about_image06.jpg" alt="">
                                <div class="member-info">
                                    <div class="member-name">John Doe</div>
                                    <div class="member-social-holder">
                                        <p>Quisque feugiat condimentum neque et mattis</p>
                                        <br>
                                        <div class="social"><a href="http://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></div>
                                        <div class="social"><a href="http://facebook.com" target="_blank"><i class="fa fa-facebook"></i></a></div>
                                        <div class="social"><a href="http://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></div>
                                    </div>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
                <div class="zigzag absolute zigzag1" style="right:-80px; top:70px">
                    <img src="images/zigzag.png" alt="">
                </div>
                <div class="zigzag absolute zigzag2" style="left:-80px; top:890px">
                    <img src="images/zigzag.png" alt="">
                </div>
            </article>
        </div>

        <!--Footer-->

        <footer class="footer">
            <div class="content-1170 center-relative">
                <ul>
                    <li class="left-footer-content">
                        © 2018 All rights reserved. | Katt HTML Template <i class="fa fa-heart"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                    </li>
                    <li class="center-footer-content">
                        <a href="index.html">
                            <img src="images/katt_default_footer_logo.png" alt="Katt">
                        </a>
                    </li>
                    <li class="right-footer-contnet">
                        <a href="#">Twitter</a>
                        <a href="#">Linkedin</a>
                        <a href="#">Dribbble</a>
                        <a href="#">Instagram</a>
                    </li>
                    <li class="left-footer-content mobile">
                        © 2018 All rights reserved. | Katt HTML Template <i class="fa fa-heart"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                    </li>
                </ul>
            </div>
        </footer>



        <div class="fixed scroll-top">
            <img src="images/back_to_top.png" alt="Go Top">
        </div>


        <script type="text/javascript" src="js/jquery.js"></script>
        <script type="text/javascript" src="js/jquery.smartmenus.min.js"></script>
        <script type="text/javascript" src="js/queryloader2.min.js"></script>
        <script type="text/javascript" src="js/jquery.carouFredSel-6.0.0-packed.js"></script>
        <script type="text/javascript" src="js/jquery.mousewheel.min.js"></script>
        <script type="text/javascript" src="js/jquery.touchSwipe.min.js"></script>
        <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="js/jquery.nicescroll.min.js"></script>
        <script type="text/javascript" src="js/main.js"></script>
    </body>
</html>

kicksbyfujo/templates/contact.html
<!DOCTYPE HTML>
<html lang="en-US">

<head>
    <title>Katt - Tasty Blog Html Template</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="description" content="Template by Colorlib" />
    <meta name="keywords" content="HTML, CSS, JavaScript, PHP" />
    <meta name="author" content="Colorlib" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="shortcut icon" href="images/favicon.png" /> {% assets "home_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" /> {% endassets %}

    <!-- <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700%7CPT+Serif:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css"  href='css/clear.css' />
        <link rel="stylesheet" type="text/css"  href='css/common.css' />
        <link rel="stylesheet" type="text/css"  href='css/font-awesome.min.css' />
        <link rel="stylesheet" type="text/css"  href='css/carouFredSel.css' />
        <link rel="stylesheet" type="text/css"  href='css/sm-clean.css' />
        <link rel="stylesheet" type="text/css"  href='style.css' /> -->

    <!--[if lt IE 9]>
                <script src="js/html5.js"></script>
        <![endif]-->

</head>

<body class="contact page page-template-default">
    <div class="doc-loader"></div>

    <div class="content-1170 header-holder center-relative">
        <div class="header-logo left">
            <a href="{{ url_for('home.index') }}">
                <img src="{{ url_for('static', filename='images/katt_default_logo.png')}}" alt="Katt">
            </a>
        </div>

        <div class="header-menu">
            <div class="toggle-holder relative">
                <div id="toggle">
                    <div class="one"></div>
                    <div class="two"></div>
                    <div class="three"></div>
                </div>
            </div>

            <nav id="header-main-menu" class="big-menu">
                <ul class="main-menu sm sm-clean">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="about2.html">About 2</a>
                    </li>
                    <li>
                        <a href="about3.html">About 3</a>
                    </li>
                    <li>
                        <a href="contact.html" class="current">Contact</a>
                        <ul class="sub-menu">
                            <li>
                                <a href="contact2.html">Contact + Map</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>


    <div id="content" class="site-content">

        <div class="header-image">
            <h1 class="entry-title">Contact</h1>
            <img src="{{ url_for('static', filename='demo-images/katt_contact_image01.jpg')}}" alt="">
        </div>
        <article class="content-1170 center-relative">
            <div class="content-wrapper">
                <div class="entry-content">
                    <!-- <div class="one_half ">
                        <p>
                            <strong>Stay in touch</strong>
                        </p>
                        <p>We choose to go to the moon in this decade and do the other things, not because they are easy.</p>
                        <br>
                        <p>Because they are hard, because that goal will serve to organize and measure the best of our energies
                            and skills, because that challenge is one that we are willing to accept, one we are unwilling
                            to postpone and one.</p>
                        <br>
                        <p>
                            <span style="color: #cdc8c1;">Address:</span>&nbsp;New York, NY, United States
                            <br>
                            <span style="color: #cdc8c1;">Phone:</span> +1 234-567-890
                            <br>
                            <span style="color: #cdc8c1;">Hours:</span> 6:00 am – 2:00 am
                            <br>
                        </p>
                    </div> -->
                    {% block login %}{% endblock %}
                    
                    <!-- <div class="contact_form">
                        <div class="contact-form">
                            <p>
                                <input id="name" type="text" name="your-name" placeholder="Name">
                            </p>
                            <p>
                                <input id="contact-email" type="email" name="your-email" placeholder="Email">
                            </p>
                            <p>
                                <input id="subject" type="text" name="your-subject" placeholder="Subject">
                            </p>
                            <p>
                                <textarea id="message" name="your-message" placeholder="Message"></textarea>
                            </p>
                            <p>
                                <input type="submit" onClick="SendMail()" value="SEND">
                            </p>
                        </div>
                    </div> -->
                    <div class="clear"></div>
                </div>
            </div>
        </article>

    </div>

    <!--Footer-->

    <footer class="footer">
        <div class="content-1170 center-relative">
            <ul>
                <li class="left-footer-content">
                    © 2018 All rights reserved. | Katt HTML Template
                    <i class="fa fa-heart"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                </li>
                <li class="center-footer-content">
                    <a href="index.html">
                        <img src="{{ url_for('static', filename='images/katt_default_footer_logo.png')}}" alt="Katt">
                    </a>
                </li>
                <li class="right-footer-contnet">
                    <a href="#">Twitter</a>
                    <a href="#">Linkedin</a>
                    <a href="#">Dribbble</a>
                    <a href="#">Instagram</a>
                </li>
                <li class="left-footer-content mobile">
                    © 2018 All rights reserved. | Katt HTML Template
                    <i class="fa fa-heart"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                </li>
            </ul>
        </div>
    </footer>



    <div class="fixed scroll-top">
        <img src="{{ url_for('static', filename='images/back_to_top.png')}}" alt="Go Top">
    </div>
    {% assets "home_js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script> 
    {% endassets %}

    <!-- <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/jquery.smartmenus.min.js"></script>
    <script type="text/javascript" src="js/queryloader2.min.js"></script>
    <script type="text/javascript" src="js/jquery.carouFredSel-6.0.0-packed.js"></script>
    <script type="text/javascript" src="js/jquery.mousewheel.min.js"></script>
    <script type="text/javascript" src="js/jquery.touchSwipe.min.js"></script>
    <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="js/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script> -->
</body>

</html>

kicksbyfujo/templates/contact2.html
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <title>Katt - Tasty Blog Html Template</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="description" content="Template by Colorlib" />
        <meta name="keywords" content="HTML, CSS, JavaScript, PHP" />
        <meta name="author" content="Colorlib" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link rel="shortcut icon" href="images/favicon.png" />
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700%7CPT+Serif:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css"  href='css/clear.css' />
        <link rel="stylesheet" type="text/css"  href='css/common.css' />
        <link rel="stylesheet" type="text/css"  href='css/font-awesome.min.css' />
        <link rel="stylesheet" type="text/css"  href='css/carouFredSel.css' />
        <link rel="stylesheet" type="text/css"  href='css/sm-clean.css' />
        <link rel="stylesheet" type="text/css"  href='style.css' />

        <!--[if lt IE 9]>
                <script src="js/html5.js"></script>
        <![endif]-->

    </head>

    <body class="contact page page-template-default">
        <div class="doc-loader"></div>

        <div class="content-1170 header-holder center-relative">
            <div class="header-logo left">
                <a href="index.html">
                    <img src="images/katt_default_logo.png" alt="Katt">
                </a>
            </div>

            <div class="header-menu">
                <div class="toggle-holder relative">
                    <div id="toggle">
                        <div class="one"></div>
                        <div class="two"></div>
                        <div class="three"></div>
                    </div>
                </div>

                <nav id="header-main-menu" class="big-menu">
                    <ul class="main-menu sm sm-clean">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="about.html">About</a></li>
                        <li><a href="about2.html">About 2</a></li>
                        <li><a href="about3.html">About 3</a></li>
                        <li><a href="contact.html">Contact</a>
                            <ul class="sub-menu">
                                <li><a href="contact2.html" class="current">Contact + Map</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>

        <div id="content" class="site-content">

            <div class="header-image">
                <h1 class="entry-title">Contact + Map</h1>
                <img src="demo-images/katt_contact_image01.jpg" alt="">
            </div>
            <article class="content-1170 center-relative">
                <div class="content-wrapper">
                    <div class="entry-content">
                        <div class="one_half">
                            <p><strong>Stay in touch</strong></p>
                            <p>We choose to go to the moon in this decade and do the other things, not because they are easy.</p>
                            <br>
                            <p>Because they are hard, because that goal will serve to organize and measure the best of our energies and skills, because that challenge is one that we are willing to accept, one we are unwilling to postpone and one.</p>
                            <br>
                            <p>
                                <span style="color: #cdc8c1;">Address:</span>&nbsp;New York, NY, United States
                                <br>
                                <span style="color: #cdc8c1;">Phone:</span> +1 234-567-890
                                <br>
                                <span style="color: #cdc8c1;">Hours:</span> 6:00 am – 2:00 am
                                <br>
                            </p>
                        </div>
                        <div class="one_half last ">
                            <br>
                            <p>
                                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d4274.290564544589!2d-75.2952832049782!3d40.753669641460846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2srs!4v1444506658649" width="600" height="450" frameborder="0" style="border:0" allowfullscreen=""></iframe>
                                <br>
                            </p>
                        </div>
                        <div class="clear"></div>
                        <br>
                        <br>
                        <div class="contact-form">
                            <p><input id="name" type="text" name="your-name" placeholder="Name"></p>
                            <p><input id="contact-email" type="email" name="your-email" placeholder="Email"></p>
                            <p><input id="subject" type="text" name="your-subject" placeholder="Subject"></p>
                            <p><textarea id="message" name="your-message" placeholder="Message"></textarea></p>
                            <p><input type="submit" onClick="SendMail()" value="SEND"></p>
                        </div>
                    </div>
                </div>
            </article>
        </div>

        <!--Footer-->

        <footer class="footer">
            <div class="content-1170 center-relative">
                <ul>
                    <li class="left-footer-content">
                        © 2018 All rights reserved. | Katt HTML Template <i class="fa fa-heart"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                    </li>
                    <li class="center-footer-content">
                        <a href="index.html">
                            <img src="images/katt_default_footer_logo.png" alt="Katt">
                        </a>
                    </li>
                    <li class="right-footer-contnet">
                        <a href="#">Twitter</a>
                        <a href="#">Linkedin</a>
                        <a href="#">Dribbble</a>
                        <a href="#">Instagram</a>
                    </li>
                    <li class="left-footer-content mobile">
                        © 2018 All rights reserved. | Katt HTML Template <i class="fa fa-heart"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>.
                    </li>
                </ul>
            </div>
        </footer>



        <div class="fixed scroll-top">
            <img src="images/back_to_top.png" alt="Go Top">
        </div>


        <script type="text/javascript" src="js/jquery.js"></script>
        <script type="text/javascript" src="js/jquery.smartmenus.min.js"></script>
        <script type="text/javascript" src="js/queryloader2.min.js"></script>
        <script type="text/javascript" src="js/jquery.carouFredSel-6.0.0-packed.js"></script>
        <script type="text/javascript" src="js/jquery.mousewheel.min.js"></script>
        <script type="text/javascript" src="js/jquery.touchSwipe.min.js"></script>
        <script type="text/javascript" src="js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="js/jquery.nicescroll.min.js"></script>
        <script type="text/javascript" src="js/main.js"></script>
    </body>
</html>

kicksbyfujo/templates/login_form.html
{% extends "contact.html" %} 

{% block login %}
<div class="contact_form">
    <form action="" method="post">
        <div class="contact-form">
            {{ form.hidden_tag() }}
            <p>
                <input id="name" type="text" name="your-name" placeholder="Name">
            </p>
            <p>
                <input id="contact-email" type="email" name="your-email" placeholder="Email">
            </p>
            <p>
                <input id="subject" type="text" name="your-subject" placeholder="Subject">
            </p>
            <p>
                <textarea id="message" name="your-message" placeholder="Message"></textarea>
            </p>
            <p>
                <input type="submit" onClick="SendMail()" value="SEND">
            </p>
        </div>
    </form>
</div>
{% endblock %}